"""Saved outputs generated by the official DepthmapX 0.9.1 executable."""
import json,math
from pathlib import Path
import pytest
from topologicpy.TGraph import TGraph

def fixture_paths():
    root=Path(__file__).parent
    return root/'fixtures/depthmap/barnsbury_segment_connections.json',root/'fixtures/depthmap/barnsbury_tulip_reference.json'

def build(endpoints):
    g=TGraph(allowSelfLoops=False);points=[]
    for p,q in endpoints:
        ends=[]
        for point in (p,q):
            i=next((i for i,v in enumerate(points) if math.dist(point,v)<=1e-5),None)
            if i is None:
                i=len(points);points.append(point);g.AddVertex(dict(zip(('x','y','z'),point)))
            ends.append(i)
        g.AddEdge(*ends)
    return g

@pytest.mark.parametrize('run_index',range(9))
def test_depthmap_saved_radius_and_weighting(run_index):
    geometry,reference=fixture_paths()
    endpoints=json.loads(geometry.read_text())['endpoints']
    run=json.loads(reference.read_text())['runs'][run_index]
    g=build(endpoints)
    kwargs={k:run[k] for k in ('radius','radiusType','weighting','tulipBins')}
    kwargs.update(algorithm='tulip',mantissa=None)
    for method,metric,fn in [('depthmap','choice',TGraph.AngularChoice),
        ('depthmap','integration',TGraph.AngularIntegration),
        ('nain','nain',TGraph.AngularIntegration),('nach','nach',TGraph.AngularChoice)]:
        values=fn(g,method=method,**kwargs)
        assert values==pytest.approx(run['expected'][metric],rel=2e-7,abs=2e-7)
        if metric=='choice' and run['weighting'] is None:
            assert values==run['expected'][metric]
    records,states,starts,adj,directed=TGraph._AngularStateData(g)
    transitions=[(*states[i],*states[j],cost) for i,neighbors in enumerate(adj) for j,cost in neighbors]
    stats=TGraph._AngularTulipValues(transitions,[math.dist(*e) for e in endpoints],
        bins=run['tulipBins'],radius=run['radius'],radiusType=run['radiusType'],
        weighting=run['weighting'],returnStats=True)
    assert stats['nodeCount']==run['expected']['nodeCount']
    for key in ('totalDepth','totalWeight'):
        for i,n in enumerate(stats['nodeCount']):
            if n>1:
                assert stats[key][i]==pytest.approx(run['expected'][key][i],rel=2e-7,abs=2e-7)

def chain():
    return [((0,0,0),(2,0,0)),((2,0,0),(2,3,0)),((2,3,0),(6,3,0))]

@pytest.mark.parametrize('radiusType,radius,expected',[
    ('metric',2,[0,0,0]),('metric',3,[0,0,0]),('metric',6,[0,2,0]),
    ('topological',0,[0,0,0]),('topological',1,[0,0,0]),('topological',2,[0,2,0]),
    ('angular',0,[0,0,0]),('angular',1,[0,0,0]),('angular',2,[0,2,0])])
def test_tulip_hand_checked_radius_chain(radiusType,radius,expected):
    g=build(chain())
    assert TGraph.AngularChoice(g,method='depthmap',algorithm='tulip',radius=radius,radiusType=radiusType)==expected

def test_weighted_endpoints_and_integration():
    g=build(chain())
    kwargs=dict(algorithm='tulip',weighting='length',mantissa=None)
    assert TGraph.AngularChoice(g,method='depthmap',**kwargs)==[14,34,20]
    assert TGraph.AngularIntegration(g,method='depthmap',**kwargs)==pytest.approx([81/11,81/6,81/7])
    assert TGraph.AngularIntegration(g,method='nain',**kwargs)==pytest.approx([9**1.2/13,9**1.2/8,9**1.2/9])
    assert [e['dictionary']['integration'] for e in g._edges]==TGraph.AngularIntegration(g,method='nain',**kwargs)

def test_isolated_straight_and_empty_integration():
    options=dict(algorithm='tulip',mantissa=None)
    assert TGraph.AngularIntegration(TGraph(),method='nain',**options)==[]
    isolated=build([((0,0,0),(1,0,0))])
    assert TGraph.AngularIntegration(isolated,method='nain',**options)==[-1]
    straight=build([((0,0,0),(1,0,0)),((1,0,0),(2,0,0))])
    assert TGraph.AngularIntegration(straight,method='depthmap',**options)==[-1,-1]
    assert TGraph.AngularIntegration(straight,method='nain',**options)==pytest.approx([2**1.2/2]*2)

@pytest.mark.parametrize('run_index',[0,1])
def test_tied_grid_depthmap_reference(run_index):
    root=Path(__file__).parent
    path=root/'fixtures/depthmap/grid_tulip_reference.json'
    fixture=json.loads(path.read_text());run=fixture['runs'][run_index]
    g=build(fixture['endpoints'])
    kwargs={key:run[key] for key in ('radius','radiusType','weighting')}
    kwargs.update(algorithm='tulip',mantissa=None,method='depthmap')
    assert TGraph.AngularChoice(g,**kwargs)==run['expected']['choice']
    assert TGraph.AngularIntegration(g,**kwargs)==pytest.approx(run['expected']['integration'],rel=1e-7)

@pytest.mark.parametrize('kwargs',[{'radius':-1},{'radius':float('nan')},
    {'radius':float('inf')},{'radius':True},{'radius':1.25},{'radiusType':'wrong'},
    {'weighting':'wrong'},{'tulipBins':1025},{'algorithm':'wrong'},
    {'method':'closeness'},{'mode':'wrong'}])
def test_invalid_tulip_integration(kwargs):
    options=dict(algorithm='tulip',method='depthmap',silent=True);options.update(kwargs)
    assert TGraph.AngularIntegration(build(chain()),**options) is None

@pytest.mark.parametrize('weighting',[None,'length'])
@pytest.mark.parametrize('radiusType,radius',[('angular',None),('angular',1),('metric',3),('topological',2)])
def test_segment_graph_matches_numeric_graph(weighting,radiusType,radius):
    from topologicpy.Edge import Edge
    from topologicpy.Vertex import Vertex
    endpoints=chain();g=build(endpoints)
    sg=TGraph.SegmentGraph([Edge.ByVertices(Vertex.ByCoordinates(*p),Vertex.ByCoordinates(*q)) for p,q in endpoints])
    options=dict(algorithm='tulip',radius=radius,radiusType=radiusType,weighting=weighting,mantissa=None)
    for fn,method in [(TGraph.AngularChoice,'depthmap'),(TGraph.AngularIntegration,'depthmap'),
                      (TGraph.AngularChoice,'nach'),(TGraph.AngularIntegration,'nain')]:
        assert fn(sg,method=method,**options)==pytest.approx(fn(g,method=method,**options))
    assert all('integration' in r['dictionary'] for r in sg._vertices)

if __name__=='__main__':
    raise SystemExit(pytest.main([__file__,'work/test_choice_tulip.py','-q','-p','no:cacheprovider','-o','addopts=']))
