# TODO: setup auto-update pixi.lock https://pixi.sh/latest/advanced/updates_github_actions/#how-to-use

name: Build tutorials

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.0
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'add-pixi' }}
      - run: pixi run install-openstudio # NOTE: can openstudio be installable from prefix channel?
      - run: pixi run tutorials
      - name: Push docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: tutorials/_site
